dependencies:
#  - name: div-cos
#    version: ~1.3.0
#    repository: '@hmctspublic'
#  - name: div-cms
#    version: ~1.2.1
#    repository: '@hmctspublic'
#  - name: div-dgs
#    version: ~1.2.0
#    repository: '@hmctspublic'
#  - name: div-emca
#    version: ~1.2.0
#    repository: '@hmctspublic'
  - name: div-fps
    version: ~1.2.1
    repository: '@hmctspublic'
#  - name: draft-store-service
#    version: ~1.0.4
#    repository: '@hmctspublic'
#  - name: rpe-service-auth-provider
#    version: ~0.1.1
#    repository: '@hmctspublic'
#  - name: cmc-pdf-service
#    version: ~0.1.3
#    repository: '@hmctspublic'
#  - name: fees-register-api
#    version: ~0.0.4
#    repository: '@hmctspublic'
#  - name: payment-api
#    version: ~0.0.4
#    repository: '@hmctspublic'
#  - name: dm-store
#    version: ~1.0.1
#    repository: '@hmctspublic'
#  - name: rpe-send-letter-service
#    version: ~0.0.4
#    repository: '@hmctspublic'
#  - name: ccd
#    version: ~3.0.4
#    repository: '@hmctspublic'
