dependencies:
  - name: div-hm
    version: ~1.1.0
    repository: '@hmctspublic'
  - name: postgresql
    version: ~5.3.0
    repository: '@stable'
  - name: div-cos
    version: ~1.3.0
    repository: '@hmctspublic'
  - name: div-cms
    version: ~1.2.1
    repository: '@hmctspublic'
  - name: div-dgs
    version: ~1.2.0
    repository: '@hmctspublic'
  - name: div-cfs
    version: ~1.1.0
    repository: '@hmctspublic'
  - name: div-emca
    version: ~1.2.0
    repository: '@hmctspublic'
  - name: div-fps
    version: ~1.2.1
    repository: '@hmctspublic'
  - name: div-pfe
    version: ~1.1.2
    repository: '@hmctspublic'
#  - name: div-rfe
#    version: ~1.1.2
#    repository: '@hmctspublic'
#  - name: div-dn
#    version: ~1.1.2
#    repository: '@hmctspublic'
#  - name: div-da
#    version: ~1.1.1
#    repository: '@hmctspublic'
  - name: draft-store-service
    version: ~1.4.1
    repository: '@hmctspublic'
  - name: rpe-service-auth-provider
    version: ~0.2.4
    repository: '@hmctspublic'
  - name: cmc-pdf-service
    version: ~0.2.1
    repository: '@hmctspublic'
  - name: fees-register-api
    version: ~0.0.4
    repository: '@hmctspublic'
  - name: payment-api
    version: ~0.1.1
    repository: '@hmctspublic'
  - name: dm-store
    version: ~2.0.2
    repository: '@hmctspublic'
  - name: rpe-send-letter-service
    version: ~0.0.7
    repository: '@hmctspublic'
  - name: ccd
    version: 4.0.4-alpha
    repository: '@hmctspublic'
  - name: ccpay-bubble-frontend
    version: 0.0.5
    repository: '@hmctspublic'
  - name: ccpay-bulkscanning-api
    version: 0.0.4
    repository: '@hmctspublic'
