tags:
  div-ccd-stack: true                   # claim-store chart
  idam-pr: true                         # citizen-frontend chart - will add IDAM redirect urls
  ccd-idam-pr: true                     # claim-store chart - will add IDAM redirect urls
  rpe-feature-toggle-api-pod: true      # citizen-frontend dep
  postgresql-pod: false                 # any chart specific postgres
  blobstorage: false                    # blob storage for dm-store

### Divorce Services ###
div-hm:
  nodejs:
    ingressHost: ""
    image: hmctspublic.azurecr.io/div/hm:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "hm-patryk-div"

div-cos:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/div/cos:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "cos-patryk-div"
    environment:
      IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
      FEATURE_DN_REFUSAL: "true"
      FEATURE_RESP_SOLICITOR_DETAILS: "true"
      SCHEDULER_SEND_UPDATED_CASES_TO_ROBOTICS_ENABLED: true
      BULKACTION_MINCASES: 5
      DATAEXTRACTION_STATUS_DA_EMAILTO: da_data_extraction@sharklasers.com
      DATAEXTRACTION_STATUS_DN_EMAILTO: dn_data_extraction@sharklasers.com
      DATAEXTRACTION_STATUS_AOS_EMAILTO: aos_data_extraction@sharklasers.com
      CASE_MAINTENANCE_SERVICE_API_BASEURL: "http://div-cms-patryk-div"
      PAYMENT_API_BASEURL: "http://payment-api-patryk-div"
      FEATURE_TOGGLE_SERVICE_API_BASEURL: "http://rpe-feature-toggle-api-pod"
      SEND_LETTER_SERIVCE_BASEURL: "http://rpe-send-letter-service-patryk-div"
      IDAM_API_REDIRECT_URL: "https://div-pfe-patryk-div"
      CASE_FORMATTER_SERVICE_API_BASEURL: "http://div-cfs-patryk-div"
      SERVICE_AUTH_PROVIDER_URL: "http://rpe-service-auth-provider-patryk-div"
      DOCUMENT_GENERATOR_SERVICE_API_BASEURL: "http://div-dgs-patryk-div"
      FEES_AND_PAYMENTS_SERVICE_API_BASEURL: "http://div-fps-patryk-div"
      SERVICE_AUTH_MICROSERVICE: "divorce_frontend"
      MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"
      SCHEDULER_RE_CREATE: true
      SCHEDULER_ENABLED: true
      DIV_SCHEDULER_DB_HOST: "div-cos-{{ .Values.global.environment }}.postgres.database.azure.com"
      DIV_SCHEDULER_DB_PORT: "5432"
      DIV_SCHEDULER_DB_NAME: "div_scheduler"
      DIV_SCHEDULER_DB_USER_NAME: "div_scheduler@div-cos-{{ .Values.global.environment }}"
      FLYWAY_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/div_scheduler"
      FLYWAY_NOOP_STRATEGY: true
      SPRING_MAIL_HOST: mta.reform.hmcts.net
      SPRING_MAIL_PORT: 25
      SPRING_MAIL_TEST_CONNECTION: false
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: mta.reform.hmcts.net
      SCHEDULER_SEND_UPDATED_CASES_TO_ROBOTICS_CRON: "0 0 2 ? * * *"

div-cms:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/div/cms:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "cms-patryk-div"
    environment:
      IDAM_API_BASEURL: "https://idam-api.aat.platform.hmcts.net"
      AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-patryk-div"
      DRAFT_STORE_API_BASEURL: "http://draft-store-service-patryk-div"
      CASE_FORMATTER_SERVICE_API_BASEURL: "http://cfs-patryk-div"
      IDAM_API_REDIRECT_URL: "https://div-pfe-patryk-div/authenticated"
      # hardocded as ccd image creates this service
      CASE_DATA_STORE_BASEURL: "http://ccd-data-store"
      AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE: "divorce_ccd_submission"
      AUTH_PROVIDER_SERVICE_CLIENT_TOKENTIMETOLIVEINSECONDS: "900"
      LOG_LEVEL: DEBUG
      MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"
      DOCUMENTATION_SWAGGER_ENABLED: true

div-dgs:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/div/dgs:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "dgs-patryk-div"
    environment:
      MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"
      FEATURE_RESP_SOLICITOR_DETAILS: "true"
      DOCMOSIS_SERVICE_DEV_MODE_FLAG: "true"
      PDF_TEST_ENABLED: "true"
      AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-{{ .Release.Name }}"
      EVIDENCE_MANAGEMENT_CLIENT_API_BASEURL: "http://emca-{{ .Release.Name }}"
      IDAM_S2S_URL: "http://rpe-service-auth-provider-{{ .Release.Name }}"
      PDF_SERVICE_BASEURL: "http://cmc-pdf-service-{{ .Release.Name }}"
      DOCMOSIS_SERVICE_BASE_URL: "https://docmosis-development.platform.hmcts.net"
      REFORM_SERVICE_NAME: "dgs"
      REFORM_TEAM: "div"
      AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE: "divorce_document_generator"
      AUTH_PROVIDER_SERVICE_CLIENT_TOKENTIMETOLIVEINSECONDS: "900"
      EVIDENCE_MANAGEMENT_CLIENT_API_HEALTH_ENDPOINT: "/health"

div-emca:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/div/emca:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "emca-patryk-div"
    environment:
      IDAM_API_HEALTH_URI: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/health"
      IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
      AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-patryk-div"
      DOCUMENT_MANAGEMENT_STORE_URL: "http://dm-store-patryk-div"
      EVIDENCE_MANAGEMENT_HEALTH_URL: "http://dm-store-patryk-div/health"
      EVIDENCE_MANAGEMENT_UPLOAD_FILE_URL: "http://dm-store-patryk-div/documents"
      AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE: "divorce_document_generator"
      AUTH_PROVIDER_SERVICE_CLIENT_TOKENTIMETOLIVEINSECONDS: "900"
      HTTP_CONNECT_REQUEST_TIMEOUT: "60000"
      HTTP_CONNECT_SOCKET_TIMEOUT: "5000"
      HTTP_CONNECT_TIMEOUT: "60000"

div-cfs:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/div/cfs:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "cfs-patryk-div"
    environment:
      DOCUMENT_MANAGEMENT_STORE_URL: "http://dm-store-patryk-div"
      REFORM_ENVIRONMENT: "demo"
      MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"

div-fps:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/div/fps:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "fps-patryk-div"
    environment:
      FEE_API_URL: "http://fees-patryk-div"

########################

##### DEPENDENCIES #####
rpe-send-letter-service:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/rpe/send-letter-service:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "rpe-send-letter-service-patryk-div"
    environment:
      FILE_CLEANUP_ENABLED: true
      LETTER_TRACKING_DB_HOST: "{{ .Release.Name }}-postgresql"
      LETTER_TRACKING_DB_NAME: "send_letter"
      LETTER_TRACKING_DB_USER_NAME: "hmcts"
      LETTER_TRACKING_DB_PASSWORD: "hmcts"
      LETTER_TRACKING_DB_CONN_OPTIONS: ""
      FLYWAY_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/send_letter?sslmode=require"
      FLYWAY_NOOP_STRATEGY: "false"
      S2S_URL: "http://rpe-service-auth-provider-patryk-div"
      ENCRYPTION_ENABLED: "false"
      APPINSIGHTS_INSTRUMENTATIONKEY: 00000000-0000-0000-0000-000000000000

dm-store:
  java:
    image: hmctspublic.azurecr.io/dm/store:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    secrets:
      STORAGE_ACCOUNT_NAME:
        disabled: true
      STORAGE_ACCOUNT_KEY:
        disabled: true
      STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:
        disabled: true
    releaseNameOverride: "dm-store-patryk-div"
    environment:
      ENABLE_DB_MIGRATE: 'true'
      ENABLE_TTL: 'false'
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts
      ENABLE_AZURE_STORAGE_CONTAINER: 'false'
      POSTGRES_STORAGE_ENABLED: 'true'
      STORAGEACCOUNT_PRIMARY_CONNECTION_STRING: 'DefaultEndpointsProtocol=https;AccountName=AAAAAAAAAAAAAAAA;AccountKey=AAAAAAAAAAAAAAAA;EndpointSuffix=core.windows.net'
      CASE_WORKER_ROLES: caseworker-divorce-courtadmin,caseworker-divorce-courtadmin-la
      SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/evidence"

cmc-pdf-service:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/cmc/pdf-service:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "cmc-pdf-service-patryk-div"
#    releaseNameOverride: "cmc-pdf-service-{{ .Release.Name }}"

draft-store-service:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/draft-store/service:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "draft-store-service-patryk-div"
    environment:
      DRAFT_STORE_DB_HOST: "{{ .Release.Name }}-postgresql"
      DRAFT_STORE_DB_NAME: draftstore
      DRAFT_STORE_DB_USER_NAME: "hmcts"
      DRAFT_STORE_DB_PASSWORD: "hmcts"
      RUN_DB_MIGRATION_ON_STARTUP: true
      DRAFT_STORE_DB_CONN_OPTIONS: ""

fees-register-api:
  java:
    image: hmctspublic.azurecr.io/fees-register/api:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 45
    livenessPeriod: 45
    releaseNameOverride: "fees-patryk-div"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/fees_register"
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts
      SPRING_LIQUIBASE_ENABLED: true
      ENABLE_FEE_LOADER: true

payment-api:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/payment/api:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "payment-api-patryk-div"
    environment:
      PAYMENT_AUDIT_FILE: /tmp/payment-audit.log
      ASB_CONNECTION_STRING: false
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/payment_api"

rpe-service-auth-provider:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/rpe/service-auth-provider:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "rpe-service-auth-provider-patryk-div"
    environment:
      TESTING_SUPPORT_ENABLED: 'true'
      MICROSERVICEKEYS_EM_GW: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_DATA: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_DEFINITION: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_GATEWAY: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_GW: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_DG_DOCASSEMBLY_API: AAAAAAAAAAAAAAAA

postgresql:
  # postgresqlConfiguration: { "maxConnections": 300 }
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "draftstore" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "fees_register" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "payment_api" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "send_letter" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "evidence" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "div_scheduler" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: user-profile
  persistence:
    enabled: false

ccd:
  postgresql:
    enabled: false
  rpeServiceAuthProvider:
    enabled: false
  draftStoreService:
    enabled: false
  dmStore:
    enabled: false
  paymentApi:
    enabled: false
  managementWeb:
    enabled: true
  apiGatewayWeb:
    enabled: true
  adminWeb:
    enabled: true
  printService:
    enabled: true
  activityApi:
    enabled: true
  testStubsService:
    enabled: true
#  ingressHost: ""
#  readinessDelay: 180
#  livenessDelay: 180
#  readinessPeriod: 60
#  livenessPeriod: 60
#  releaseNameOverride: "ccd-patryk-div"
#  adminWeb:
#    enabled: true
#    environment:
#      NODE_TLS_REJECT_UNAUTHORIZED: 0
#  caseManagementWeb:
#    enabled: true
#    environment:
#      NODE_TLS_REJECT_UNAUTHORIZED: 0
#  importer:
#    userprofile:
#      enabled:
#      jurisdictions:
#        - DIVORCE
#      users:
#        - divorce_as_caseworker_beta@mailinator.com|DIVORCE|DIVORCE|Submitted
#        - divorce_as_caseworker_solicitor@mailinator.com|DIVORCE|DIVORCE|Submitted
#        - divorce_as_caseworker_bulk_scanner@mailinator.com|DIVORCE|DIVORCE|Submitted
#        - divorce_as_caseworker_superuser@mailinator.com|DIVORCE|DIVORCE|Submitted
#        - divorce_as_caseworker_la@mailinator.com|DIVORCE|DIVORCE|Submitted
#        - divorce_as_caseworker_admin@mailinator.com|DIVORCE|DIVORCE|Submitted
#        - divorce_respondent_solicitor@mailinator.com|DIVORCE|DIVORCE|Submitted
#      userProfileDatabaseHost: patryk-div-postgresql
#      userProfileDatabasePort: 5432
#      userProfileDatabaseUser: hmcts
#      userProfileDatabasePassword: hmcts
#      userProfileDatabaseName: user-profile
